version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run main script
          command: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run tests
          command: python -m unittest tests.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
